name: "Bump Spicetify Packages"

on:
  push:
    paths:
      - 'pkgs/nvfetcher.toml'
      - 'flake.lock'
  repository_dispatch:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NIXPKGS_ALLOW_UNFREE: 1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install nix
      uses: DeterminateSystems/nix-installer-action@main
            
    - name: Run nvfetcher
      run: |
        nix run github:berberman/nvfetcher -- -o pkgs/_sources -c pkgs/nvfetcher.toml

    - name: Show flake metadata
      run: nix flake metadata --impure

    - name: Build nix packages
      run: nix build .#checks.x86_64-linux.default --impure -v

    - name: Push updates
      if: ${{ success() }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Bump Spicetify Packages"
        file_pattern: "pkgs/_sources/"
